### ISSUE TITLE
credentials

### ISSUE THREAD

**Issue by NafunaAfrica** [TheFehr/n8n-nodes-pocketbase#4]
I installed this from the community nodes section. its there but when i put the node in my flow it needs credentials and i dont know where to put them

**Comment by TheFehr** [comment]
You should be able to create a new credential entry, just like any other n8n node that needs credentials

**Comment by NafunaAfrica** [comment]
![image](https://github.com/TheFehr/n8n-nodes-pocketbase/assets/84924809/f4645abf-4603-4a0e-8225-22caaf81d130)
Here is what I see

**Comment by TheFehr** [comment]
That is weird, I'd need to check it on a fresh install myself tomorrow.
What you could try is create the Credentials first outside of the workflow.

**Comment by NafunaAfrica** [comment]
on my end i now get create credentials. I am using self hosted but get error. Wanted to know what "User collection name" is?is that the collection I am accessing? I also then see a Resource field after, what's meant to go so i connect?

**Comment by TheFehr** [comment]
I am happy to hear that it works.

**Comment by Igloczek** [comment]
I've just had the same problem as OP, but it wasn't just for this package. Every one that I installed was adding just nodes, but no credentials. Switched the docker image to an older one, in my case 1.48.3, and it started working 🤷 

But I have a different question @TheFehr, why the credentials flow is only for users, not admins? For me, it's quite weird to even support regular users flows, since it requires having a fake admin user and granting him permissions, which will make mess on the Pocketbase side or will lead to security problems, when we leave everything open.

Workflow like this are usually meant to handle admin actions, not user scoped stuff, since we can't authenticate as users dynamically.
